%% Script: run_mex
%
% Description: This script generates mex files for the evaluation of 
% dynamics and holonomic constraints.
%
% Author: Jenna Reher, jreher@caltech.edu
% _____________________________________________________________________

mex('-O', [pwd, '/evaluate_dynamics.cpp'],...
	[pwd, '/src/De_cassie_v4.cc'], ...
    [pwd, '/src/Ge_cassie_v4.cc'], ...
    ['-I', pwd, '/src/'])


mex('-O', [pwd, '/evaluate_holonomics.cpp'],...
	[pwd, '/src/J_achilles_constraint.cc'], ...
    [pwd, '/src/J_left_fixed_constraint.cc'], ...
    [pwd, '/src/J_right_fixed_constraint.cc'], ...
    [pwd, '/src/J_leftSole_constraint.cc'], ...
    [pwd, '/src/J_rightSole_constraint.cc'], ...
    [pwd, '/src/Jdot_achilles_constraint.cc'], ...
    [pwd, '/src/Jdot_left_fixed_constraint.cc'], ...
    [pwd, '/src/Jdot_right_fixed_constraint.cc'], ...
    [pwd, '/src/Jdot_leftSole_constraint.cc'], ...
    [pwd, '/src/Jdot_rightSole_constraint.cc'], ...
    ['-I', pwd, '/src/'])